/*
  Copyright (c) 2011, Digital Media Professionals. All rights reserved.
*/
#ifndef __EGL_NATIVE_PHLOX_H__
#define __EGL_NATIVE_PHLOX_H__

#ifdef __cplusplus
extern "C" {
#endif


#define	EGL_NATIVE_OUTPUT_DEVICE					0xE000
#define	EGL_NATIVE_OUTPUT_DEVICE_NORMAL				0xE001
/* reserved 0xE002 - 0xE003 */
#define	EGL_NATIVE_OUTPUT_DEVICE_EXTERNAL			0xE004

#ifdef PANA_ORG_FUNC
#define	EGL_NATIVE_BACK_BUFFER_INDEX				0xE010
#define	EGL_NATIVE_PHYSICAL_ADDRESS0				0xE011
#define	EGL_NATIVE_PHYSICAL_ADDRESS1				0xE012
#define	EGL_NATIVE_YPLANE_PHYSICAL_ADDRESS0			0xE013
#define	EGL_NATIVE_YPLANE_PHYSICAL_ADDRESS1			0xE014
#define	EGL_NATIVE_UVPLANE_PHYSICAL_ADDRESS0		0xE015
#define	EGL_NATIVE_UVPLANE_PHYSICAL_ADDRESS1		0xE016

#define	EGL_NATIVE_FRAMEBUFFER_ADDRESS1				0xE017
#define	EGL_NATIVE_FRAMEBUFFER_ADDRESS_UV1			0xE018
#define	EGL_NATIVE_FRAMEBUFFER_ADDRESS2				0xE019
#define	EGL_NATIVE_FRAMEBUFFER_ADDRESS_UV2			0xE01A
#endif /* PANA_ORG_FUNC */

#ifdef __cplusplus
}
#endif

#endif /* __EGL_NATIVE_PHLOX_H__ */
