#ifndef _KERNEL_ID_H_
#define _KERNEL_ID_H_

//#include "kernel_tmax.h"

/* Generated by txiCfg */
/* Data define file. */


#define TMAX_TSK_OBJ      (124+TMAX_TSK_OBJ_AUTO)
#define TMAX_SEM_OBJ      (181+TMAX_SEM_OBJ_AUTO)
#define TMAX_FLG_OBJ      (112+TMAX_FLG_OBJ_AUTO)
#define TMAX_DTQ_OBJ       (49+TMAX_DTQ_OBJ_AUTO)
#define TMAX_MBX_OBJ       (41+TMAX_MBX_OBJ_AUTO)
#define TMAX_MTX_OBJ       (99+TMAX_MTX_OBJ_AUTO)
#define TMAX_POR_OBJ        (1+TMAX_POR_OBJ_AUTO)
#define TMAX_MPF_OBJ       (49+TMAX_MPF_OBJ_AUTO)
#define TMAX_MPL_OBJ       (31+TMAX_MPL_OBJ_AUTO)
#define TMAX_CYC_OBJ       (15+TMAX_CYC_OBJ_AUTO)
#define TMAX_ALM_OBJ       (39+TMAX_ALM_OBJ_AUTO)

#define FONT_LIBMPL_ID  19
#define GFX_RESMPL_ID      18
#define GUI_WORKMPL_ID     17

//###mada 以下仮定義
#define CT_CYC_ID			16
#define CT_DRAW_TSKID		125
#define CT_MAIN_TSKID		126
#define CT_DBG_TSKID		127

#define CT_FLGID_DRAWTASK	113
#define CT_FLGID_MAINTASK	114
#define CT_FLGID_SYNCHRO	115
#define CT_FLGID_DBGTASK	116

#define CT_MBXID_DRAW		42
#define CT_MBXID_MAIN		44
#define CT_MBXID_DBG		45

#define CT_MPL_ID			32
#define CT_FASTMPL_ID		33
#define CT_SEMID_OBJECT		182
#define CT_SEMID_RECEIVER	183
#define CT_SEMID_SYNCHRO	189
#define CT_SEMID_GDI		191
#define GDI_SEMID_FONTAPI	185
#define GDI_SEMID_DRAW		186
#define GDI_SEMID_CREATE_CACHE 187
#define GDI_SEMID_CONTEXT	188
#define AVDF_CYC_ID			17

#define GUI_TS_TSKID		128
#define GUI_TS_DTQID		46
#define GUI_TS_MPLID		34
#define GUI_TS_FLGID		74

//以下はシミュレータ用。他のものと番号が重複した場合、こちらのIDをずらすこと
#define MBXID_WIN_DRAW_TASK		47

//###mada 以下の定義はWinItron専用
#define TSKID_WINITRON		255

#endif// _KERNEL_ID_H_
