/******************************************************************************
 * Copyright(c) 2018 Persol AVC Technology.
 ******************************************************************************/
#include "CtParameterConvIf.h"

CtParamConvIf::CtParamConvIf()
{
}

CtParamConvIf::~CtParamConvIf()
{
}
	
char* CtParamConvIf::convFromUserParamToCharStr(AplParamEepromId userSwParamNo){
    switch (APL_PARAM_GET_DATA(userSwParamNo)) {
	case APL_SYS_PARAM_USER_BUTTON_INH:
		return "INHIBIT";
	case APL_SYS_PARAM_USER_BUTTON_AWB:
		return "AWB";
	case APL_SYS_PARAM_USER_BUTTON_DRS:
        return "DRS";
	case APL_SYS_PARAM_USER_BUTTON_FLASH_BAND:
		return "FBC";
    case APL_SYS_PARAM_USER_BUTTON_PUSH_AF:
        return "ONE PUSH AF";
	case APL_SYS_PARAM_USER_BUTTON_S_GAIN:
        return "S.GAIN";
	case APL_SYS_PARAM_USER_BUTTON_AREA:
        return "AREA";
	case APL_SYS_PARAM_USER_BUTTON_AF_AREA_RANGE:
        return "AF RANGE";
	case APL_SYS_PARAM_USER_BUTTON_ATW:
        return "ATW";
	case APL_SYS_PARAM_USER_BUTTON_ATW_LOCK:
        return "ATW LOCK";
	case APL_SYS_PARAM_USER_BUTTON_BACKLIGHT:
        return "BACK LIGHT";
	case APL_SYS_PARAM_USER_BUTTON_SPOTLIGHT:
        return "SPOT LIGHT";
	case APL_SYS_PARAM_USER_BUTTON_AUTO_IRIS:
        return "AUTO IRIS";
	case APL_SYS_PARAM_USER_BUTTON_IRIS:
        return "IRIS";
	case APL_SYS_PARAM_USER_BUTTON_YGET:
        return "Y GET";
	case APL_SYS_PARAM_USER_BUTTON_FOCUS_MACRO:
        return "FOCUS MACRO";
	case APL_SYS_PARAM_USER_BUTTON_OIS_MODE:
        return "OIS";
	case APL_SYS_PARAM_USER_BUTTON_D_ZOOM:
        return "D ZOOM";
	case APL_SYS_PARAM_USER_BUTTON_IA_ZOOM:
        return "IA ZOOM";
	case APL_SYS_PARAM_USER_BUTTON_IR_MODE:
	case APL_SYS_PARAM_USER_BUTTON_IR_REC:
        return "IR REC";
	case APL_SYS_PARAM_USER_BUTTON_FZOOM:
        return "FAST ZOOM";
	case APL_SYS_PARAM_USER_BUTTON_PREREC:
        return "PRE REC";
	case APL_SYS_PARAM_USER_BUTTON_VFR:
        return "VFR";
	case APL_SYS_PARAM_USER_BUTTON_SUPERSLOW:
        return "SUPER SLOW";
	case APL_SYS_PARAM_USER_BUTTON_REC_CHECK:
        return "REC CHECK";
	case APL_SYS_PARAM_USER_BUTTON_BACKGROUND:
        return "BACK GROUND";
	case APL_SYS_PARAM_USER_BUTTON_LAST_CLIP:
        return "DEL LAST CLIP";
	case APL_SYS_PARAM_USER_BUTTON_SLOT_SEL:
        return "SLOT SEL";
	case APL_SYS_PARAM_USER_BUTTON_REC_MEDIA:
        return "REC MEDIA";
	case APL_SYS_PARAM_USER_BUTTON_TEXT_MEMO:
        return "TEXT MEMO";
	case APL_SYS_PARAM_USER_BUTTON_SHOT_MARK:
        return "SHOT MARK";
	case APL_SYS_PARAM_USER_BUTTON_PEAK_SQ_FA:
        return "PEAKING";
	case APL_SYS_PARAM_USER_BUTTON_FA:
        return "FOCUS ASSIST";
	case APL_SYS_PARAM_USER_BUTTON_WFM:
        return "WFM";
	case APL_SYS_PARAM_USER_BUTTON_ZEBRA:
        return "ZEBRA";
	case APL_SYS_PARAM_USER_BUTTON_BALANCE:
        return "LEVEL GAUGE";
	case APL_SYS_PARAM_USER_BUTTON_LEVELGAGE_SET:
        return "LEVEL GAUGE SET";
	case APL_SYS_PARAM_USER_BUTTON_EVF:
        return "EVF";
	case APL_SYS_PARAM_USER_BUTTON_EVF_DTL:
        return "EVF DTL";
	case APL_SYS_PARAM_USER_BUTTON_AUDIO_MON_SEL:
        return "AUDIO MON SEL";
	case APL_SYS_PARAM_USER_BUTTON_MENU:
        return "MENU";
	case APL_SYS_PARAM_USER_BUTTON_LOAD_SETUP_FILE:
        return "LOAD SETUP FILE";
	case APL_SYS_PARAM_USER_BUTTON_POWER_LCD:
        return "LCD BACKLIGHT";
	case APL_SYS_PARAM_USER_BUTTON_CARD_READER_MODE:
        return "CARD READER MODE";
	case APL_SYS_PARAM_USER_BUTTON_NETWORK_FUNC:
        return "NETWORK FUNC";
	case APL_SYS_PARAM_USER_BUTTON_NETWORK_SSID:
        return "SSID";
	case APL_SYS_PARAM_USER_BUTTON_NETWORK_STREAM_START:
        return "STREAMING START";
	case APL_SYS_PARAM_USER_BUTTON_REC_DURING_UL:
        return "REC DURING UPLOAD";
	case APL_SYS_PARAM_USER_BUTTON_REC_UPLOAD_LIST:
        return "UPLOAD LIST";
	case APL_SYS_PARAM_USER_BUTTON_REC_EASY_IP_SET:
        return "EASY IP SETTING";
	default:
		return "Error";
		break;
	}

}

GDI_STRING_ID CtParamConvIf::convFromUserParamToStringId(int userSwNoParamData){
	switch (userSwNoParamData) {
	case APL_SYS_PARAM_USER_BUTTON_INH:
		return STR_ID_NO_10803;
	case APL_SYS_PARAM_USER_BUTTON_AWB:
		return STR_ID_NO_10804;
	case APL_SYS_PARAM_USER_BUTTON_DRS:
		return STR_ID_NO_11461;
	case APL_SYS_PARAM_USER_BUTTON_FLASH_BAND:
		return STR_ID_NO_11460;
	case APL_SYS_PARAM_USER_BUTTON_PUSH_AF:
		return STR_ID_NO_10805;
	case APL_SYS_PARAM_USER_BUTTON_S_GAIN:
		return STR_ID_NO_11477;
	case APL_SYS_PARAM_USER_BUTTON_AREA:
		return STR_ID_NO_11478;
	case APL_SYS_PARAM_USER_BUTTON_AF_AREA_RANGE:
		return STR_ID_NO_11475;
	case APL_SYS_PARAM_USER_BUTTON_ATW:
		return STR_ID_NO_10762;
	case APL_SYS_PARAM_USER_BUTTON_ATW_LOCK:
		return STR_ID_NO_10763;
	case APL_SYS_PARAM_USER_BUTTON_BACKLIGHT:
		return STR_ID_NO_11480;
	case APL_SYS_PARAM_USER_BUTTON_SPOTLIGHT:
		return STR_ID_NO_11479;
	case APL_SYS_PARAM_USER_BUTTON_AUTO_IRIS_LEVEL:
	case APL_SYS_PARAM_USER_BUTTON_AUTO_IRIS:
		return STR_ID_NO_11481;
	case APL_SYS_PARAM_USER_BUTTON_IRIS:
		return STR_ID_NO_11482;
	case APL_SYS_PARAM_USER_BUTTON_YGET:
		return STR_ID_NO_11483;
	case APL_SYS_PARAM_USER_BUTTON_FOCUS_MACRO:
		return STR_ID_NO_11484;
	case APL_SYS_PARAM_USER_BUTTON_OIS_MODE:
		return STR_ID_NO_11485;
	case APL_SYS_PARAM_USER_BUTTON_D_ZOOM:
		return STR_ID_NO_10807;
	case APL_SYS_PARAM_USER_BUTTON_IA_ZOOM:
		return STR_ID_NO_11041;
	case APL_SYS_PARAM_USER_BUTTON_IR_MODE:
	case APL_SYS_PARAM_USER_BUTTON_IR_REC:
		return STR_ID_NO_11486;
	case APL_SYS_PARAM_USER_BUTTON_FZOOM:
		return STR_ID_NO_11487;
	case APL_SYS_PARAM_USER_BUTTON_PREREC:
		return STR_ID_NO_10810;
	case APL_SYS_PARAM_USER_BUTTON_VFR:
		return STR_ID_NO_10964;
	case APL_SYS_PARAM_USER_BUTTON_SUPERSLOW:
		return STR_ID_NO_11488;
	case APL_SYS_PARAM_USER_BUTTON_REC_CHECK:
		return STR_ID_NO_10811;
	case APL_SYS_PARAM_USER_BUTTON_BACKGROUND:
	case APL_SYS_PARAM_USER_BUTTON_BACKGR_PAUSE:
		return STR_ID_NO_10812;
	case APL_SYS_PARAM_USER_BUTTON_LAST_CLIP:
		return STR_ID_NO_10813;
	case APL_SYS_PARAM_USER_BUTTON_SLOT_SEL:
		return STR_ID_NO_10814;
	//case APL_SYS_PARAM_USER_BUTTON_REC_MEDIA:
	//	//return STR_ID_NO_1;
	//	break;
	case APL_SYS_PARAM_USER_BUTTON_TEXT_MEMO:
		return STR_ID_NO_11489;
	case APL_SYS_PARAM_USER_BUTTON_SHOT_MARK:
		return STR_ID_NO_11490;
	case APL_SYS_PARAM_USER_BUTTON_PEAK_SQ_FA:
		return STR_ID_NO_11491;
	case APL_SYS_PARAM_USER_BUTTON_FA:
		return STR_ID_NO_10815;
	case APL_SYS_PARAM_USER_BUTTON_WFM:
		return STR_ID_NO_10818;
	case APL_SYS_PARAM_USER_BUTTON_ZEBRA:
		return STR_ID_NO_10820;
	case APL_SYS_PARAM_USER_BUTTON_BALANCE:
	case APL_SYS_PARAM_USER_BUTTON_LEVEL:
		return STR_ID_NO_10821;
	case APL_SYS_PARAM_USER_BUTTON_LEVELGAGE_SET:
		return STR_ID_NO_10822;
	case APL_SYS_PARAM_USER_BUTTON_EVF:
		return STR_ID_NO_11494;
	case APL_SYS_PARAM_USER_BUTTON_EVF_DTL:
		return STR_ID_NO_11495;
	case APL_SYS_PARAM_USER_BUTTON_LCDVF_HDR:
		return STR_ID_NO_11493;
	case APL_SYS_PARAM_USER_BUTTON_AUDIO_MON_SEL:
		return STR_ID_NO_11496;
	case APL_SYS_PARAM_USER_BUTTON_MENU:
		return STR_ID_NO_11497;
	case APL_SYS_PARAM_USER_BUTTON_LOAD_SETUP_FILE:
		return STR_ID_NO_11531;
	case APL_SYS_PARAM_USER_BUTTON_POWER_LCD:
		return STR_ID_NO_11499;
	case APL_SYS_PARAM_USER_BUTTON_CARD_READER_MODE:
		return STR_ID_NO_11532;
	case APL_SYS_PARAM_USER_BUTTON_NETWORK_FUNC:
		return STR_ID_NO_11501;
	/*case APL_SYS_PARAM_USER_BUTTON_NETWORK_SSID:
		return STR_ID_NO_1;*/
	case APL_SYS_PARAM_USER_BUTTON_NETWORK_STREAM_START:
		return STR_ID_NO_11533;
	case APL_SYS_PARAM_USER_BUTTON_REC_DURING_UL:
		return STR_ID_NO_11534;
	case APL_SYS_PARAM_USER_BUTTON_REC_UPLOAD_LIST:
		return STR_ID_NO_11504;
	/*case APL_SYS_PARAM_USER_BUTTON_REC_EASY_IP_SET:
		return STR_ID_NO_1;*/
	default:
		break;
	}
		
	return STR_ID_NO_10803;
}
