#ifndef __UTF16_CHAR_H__
#define __UTF16_CHAR_H__

/* ASCII */
#define UTF_A_SPACE										0x0020 /*   */
#define UTF_A_EXCLAMATION_MARK							0x0021 /* ! */
#define UTF_A_QUOTATION_MARK							0x0022 /* " */
#define UTF_A_NUMBER_SIGN								0x0023 /* # */
#define UTF_A_DOLLAR_SIGN								0x0024 /* $ */
#define UTF_A_PERCENT_SIGN								0x0025 /* % */
#define UTF_A_AMPERSAND									0x0026 /* & */
#define UTF_A_APOSTROPHE								0x0027 /* ' */
#define UTF_A_L_PARENTHESIS								0x0028 /* ( */
#define UTF_A_R_PARENTHESIS								0x0029 /* ) */
#define UTF_A_ASTERISK									0x002A /* * */
#define UTF_A_PLUS_SIGN									0x002B /* + */
#define UTF_A_COMMA										0x002C /* , */
#define UTF_A_HYPHEN_MINUS								0x002D /* - */
#define UTF_A_FULL_STOP									0x002E /* . */
#define UTF_A_SOLIDUS									0x002F /* / */
#define UTF_A_DIGIT_ZERO								0x0030 /* 0 */
#define UTF_A_DIGIT_ONE									0x0031 /* 1 */
#define UTF_A_DIGIT_TWO									0x0032 /* 2 */
#define UTF_A_DIGIT_THREE								0x0033 /* 3 */
#define UTF_A_DIGIT_FOUR								0x0034 /* 4 */
#define UTF_A_DIGIT_FIVE								0x0035 /* 5 */
#define UTF_A_DIGIT_SIX									0x0036 /* 6 */
#define UTF_A_DIGIT_SEVEN								0x0037 /* 7 */
#define UTF_A_DIGIT_EIGHT								0x0038 /* 8 */
#define UTF_A_DIGIT_NINE								0x0039 /* 9 */
#define UTF_A_COLON										0x003A /* : */
#define UTF_A_SEMICOLON									0x003B /* ; */
#define UTF_A_LESS_THAN_SIGN							0x003C /* < */
#define UTF_A_EQUALS_SIGN								0x003D /* = */
#define UTF_A_GREATER_THAN_SIGN							0x003E /* > */
#define UTF_A_QUESTION_MARK								0x003F /* ? */
#define UTF_A_COMMERCIAL_AT								0x0040 /* @ */
#define UTF_A_CAPITAL_LETTER_A							0x0041 /* A */
#define UTF_A_CAPITAL_LETTER_B							0x0042 /* B */
#define UTF_A_CAPITAL_LETTER_C							0x0043 /* C */
#define UTF_A_CAPITAL_LETTER_D							0x0044 /* D */
#define UTF_A_CAPITAL_LETTER_E							0x0045 /* E */
#define UTF_A_CAPITAL_LETTER_F							0x0046 /* F */
#define UTF_A_CAPITAL_LETTER_G							0x0047 /* G */
#define UTF_A_CAPITAL_LETTER_H							0x0048 /* H */
#define UTF_A_CAPITAL_LETTER_I							0x0049 /* I */
#define UTF_A_CAPITAL_LETTER_J							0x004A /* J */
#define UTF_A_CAPITAL_LETTER_K							0x004B /* K */
#define UTF_A_CAPITAL_LETTER_L							0x004C /* L */
#define UTF_A_CAPITAL_LETTER_M							0x004D /* M */
#define UTF_A_CAPITAL_LETTER_N							0x004E /* N */
#define UTF_A_CAPITAL_LETTER_O							0x004F /* O */
#define UTF_A_CAPITAL_LETTER_P							0x0050 /* P */
#define UTF_A_CAPITAL_LETTER_Q							0x0051 /* Q */
#define UTF_A_CAPITAL_LETTER_R							0x0052 /* R */
#define UTF_A_CAPITAL_LETTER_S							0x0053 /* S */
#define UTF_A_CAPITAL_LETTER_T							0x0054 /* T */
#define UTF_A_CAPITAL_LETTER_U							0x0055 /* U */
#define UTF_A_CAPITAL_LETTER_V							0x0056 /* V */
#define UTF_A_CAPITAL_LETTER_W							0x0057 /* W */
#define UTF_A_CAPITAL_LETTER_X							0x0058 /* X */
#define UTF_A_CAPITAL_LETTER_Y							0x0059 /* Y */
#define UTF_A_CAPITAL_LETTER_Z							0x005A /* Z */
#define UTF_A_L_SQUARE_BRACKET							0x005B /* [ */
#define UTF_A_REVERSE_SOLIDUS							0x005C /* \ */
#define UTF_A_R_SQUARE_BRACKET							0x005D /* ] */
#define UTF_A_CIRCUMFLEX_ACCENT							0x005E /* ^ */
#define UTF_A_LOW_LINE									0x005F /* _ */
#define UTF_A_GRAVE_ACCENT								0x0060 /* ` */
#define UTF_A_SMALL_LETTER_A							0x0061 /* a */
#define UTF_A_SMALL_LETTER_B							0x0062 /* b */
#define UTF_A_SMALL_LETTER_C							0x0063 /* c */
#define UTF_A_SMALL_LETTER_D							0x0064 /* d */
#define UTF_A_SMALL_LETTER_E							0x0065 /* e */
#define UTF_A_SMALL_LETTER_F							0x0066 /* f */
#define UTF_A_SMALL_LETTER_G							0x0067 /* g */
#define UTF_A_SMALL_LETTER_H							0x0068 /* h */
#define UTF_A_SMALL_LETTER_I							0x0069 /* i */
#define UTF_A_SMALL_LETTER_J							0x006A /* j */
#define UTF_A_SMALL_LETTER_K							0x006B /* k */
#define UTF_A_SMALL_LETTER_L							0x006C /* l */
#define UTF_A_SMALL_LETTER_M							0x006D /* m */
#define UTF_A_SMALL_LETTER_N							0x006E /* n */
#define UTF_A_SMALL_LETTER_O							0x006F /* o */
#define UTF_A_SMALL_LETTER_P							0x0070 /* p */
#define UTF_A_SMALL_LETTER_Q							0x0071 /* q */
#define UTF_A_SMALL_LETTER_R							0x0072 /* r */
#define UTF_A_SMALL_LETTER_S							0x0073 /* s */
#define UTF_A_SMALL_LETTER_T							0x0074 /* t */
#define UTF_A_SMALL_LETTER_U							0x0075 /* u */
#define UTF_A_SMALL_LETTER_V							0x0076 /* v */
#define UTF_A_SMALL_LETTER_W							0x0077 /* w */
#define UTF_A_SMALL_LETTER_X							0x0078 /* x */
#define UTF_A_SMALL_LETTER_Y							0x0079 /* y */
#define UTF_A_SMALL_LETTER_Z							0x007A /* z */
#define UTF_A_L_CURLY_BRACKET							0x007B /* { */
#define UTF_A_VERTICAL_LINE								0x007C /* | */
#define UTF_A_R_CURLY_BRACKET							0x007D /* } */
#define UTF_A_TILDE										0x007E /* ~ */


/* LATIN1 */
#define UTF_L_NO_BREAK_SPACE							0x00A0 /*   */
#define UTF_L_INVERTED_EXCLAMATION_MARK					0x00A1 /* ^! */
#define UTF_L_CENT_SIGN									0x00A2 /* Åë */
#define UTF_L_POUND_SIGN								0x00A3 /* Åí */
#define UTF_L_CURRENCY_SIGN								0x00A4 /*  */
#define UTF_L_YEN_SIGN									0x00A5 /* \ */
#define UTF_L_BROKEN_BAR								0x00A6 /* | */
#define UTF_L_SECTION_SIGN								0x00A7 /* Åò */
#define UTF_L_DIAERESIS									0x00A8 /* ÅN */
#define UTF_L_COPYR_SIGN								0x00A9 /* (c) */
#define UTF_L_FEMININE_ORDINAL_INDICATOR				0x00AA /* a_ */
#define UTF_L_L_POINTING_DOUBLE_ANGLE_QUOTATION_MARK	0x00AB /* Å· */
#define UTF_L_NOT_SIGN									0x00AC /* Å  */
#define UTF_L_SOFT_HYPHEN								0x00AD /* - */
#define UTF_L_REGISTERED_SIGN							0x00AE /* (R) */
#define UTF_L_MACRON									0x00AF /* ÅP */
#define UTF_L_DEGREE_SIGN								0x00B0 /* Åã */
#define UTF_L_PLUS_MINUS_SIGN							0x00B1 /* Å} */
#define UTF_L_SUPERSCRIPT_TWO							0x00B2 /* 2 */
#define UTF_L_SUPERSCRIPT_THREE							0x00B3 /* 3 */
#define UTF_L_ACUTE_ACCENT								0x00B4 /* ÅL */
#define UTF_L_MICRO_SIGN								0x00B5 /* É  */
#define UTF_L_PILCROW_SIGN								0x00B6 /* Å˜ */
#define UTF_L_MIDDLE_DOT								0x00B7 /* ÅE */
#define UTF_L_CEDILLA									0x00B8 /* ÅC */
#define UTF_L_SUPERSCRIPT_ONE							0x00B9 /* 1 */
#define UTF_L_MASCULINE_ORDINAL_INDICATOR				0x00BA /* o_ */
#define UTF_L_R_POINTING_DOUBLE_ANGLE_QUOTATION_MARK	0x00BB /* Å‚ */
#define UTF_L_VULGAR_FRACTION_ONE_QUARTER				0x00BC /* 1/4 */
#define UTF_L_VULGAR_FRACTION_ONE_HALF					0x00BD /* 1/2 */
#define UTF_L_VULGAR_FRACTION_THREE_QUARTERS			0x00BE /* 3/4 */
#define UTF_L_INVERTED_QUESTION_MARK					0x00BF /* ^? */
#define UTF_L_CAPITAL_LETTER_A_WITH_GRAVE				0x00C0 /* A` */
#define UTF_L_CAPITAL_LETTER_A_WITH_ACUTE				0x00C1 /* AÅL */
#define UTF_L_CAPITAL_LETTER_A_WITH_CIRCUMFLEX			0x00C2 /* A^ */
#define UTF_L_CAPITAL_LETTER_A_WITH_TILDE				0x00C3 /* A~ */
#define UTF_L_CAPITAL_LETTER_A_WITH_DIAERESIS			0x00C4 /* AÅN */
#define UTF_L_CAPITAL_LETTER_A_WITH_RING_ABOVE			0x00C5 /* AÅã */
#define UTF_L_CAPITAL_LETTER_AE							0x00C6 /* AE */
#define UTF_L_CAPITAL_LETTER_C_WITH_CEDILLA				0x00C7 /* CÅC */
#define UTF_L_CAPITAL_LETTER_E_WITH_GRAVE				0x00C8 /* E` */
#define UTF_L_CAPITAL_LETTER_E_WITH_ACUTE				0x00C9 /* EÅL */
#define UTF_L_CAPITAL_LETTER_E_WITH_CIRCUMFLEX			0x00CA /* E^ */
#define UTF_L_CAPITAL_LETTER_E_WITH_DIAERESIS			0x00CB /* EÅN */
#define UTF_L_CAPITAL_LETTER_I_WITH_GRAVE				0x00CC /* I` */
#define UTF_L_CAPITAL_LETTER_I_WITH_ACUTE				0x00CD /* IÅL */
#define UTF_L_CAPITAL_LETTER_I_WITH_CIRCUMFLEX			0x00CE /* I^ */
#define UTF_L_CAPITAL_LETTER_I_WITH_DIAERESIS			0x00CF /* IÅN */
#define UTF_L_CAPITAL_LETTER_ETH						0x00D0 /* D */
#define UTF_L_CAPITAL_LETTER_N_WITH_TILDE				0x00D1 /* N~ */
#define UTF_L_CAPITAL_LETTER_O_WITH_GRAVE				0x00D2 /* O` */
#define UTF_L_CAPITAL_LETTER_O_WITH_ACUTE				0x00D3 /* OÅL */
#define UTF_L_CAPITAL_LETTER_O_WITH_CIRCUMFLEX			0x00D4 /* O^ */
#define UTF_L_CAPITAL_LETTER_O_WITH_TILDE				0x00D5 /* O~ */
#define UTF_L_CAPITAL_LETTER_O_WITH_DIAERESIS			0x00D6 /* OÅN */
#define UTF_L_MULTIPLICATION_SIGN						0x00D7 /* Å~ */
#define UTF_L_CAPITAL_LETTER_O_WITH_STROKE				0x00D8 /* O/ */
#define UTF_L_CAPITAL_LETTER_U_WITH_GRAVE				0x00D9 /* U` */
#define UTF_L_CAPITAL_LETTER_U_WITH_ACUTE				0x00DA /* UÅL */
#define UTF_L_CAPITAL_LETTER_U_WITH_CIRCUMFLEX			0x00DB /* U^ */
#define UTF_L_CAPITAL_LETTER_U_WITH_DIAERESIS			0x00DC /* UÅN */
#define UTF_L_CAPITAL_LETTER_Y_WITH_ACUTE				0x00DD /* YÅL */
#define UTF_L_CAPITAL_LETTER_THORN						0x00DE /* T */
#define UTF_L_SMALL_LETTER_SHARP_S						0x00DF /* s */
#define UTF_L_SMALL_LETTER_A_WITH_GRAVE					0x00E0 /* a` */
#define UTF_L_SMALL_LETTER_A_WITH_ACUTE					0x00E1 /* aÅL */
#define UTF_L_SMALL_LETTER_A_WITH_CIRCUMFLEX			0x00E2 /* a^ */
#define UTF_L_SMALL_LETTER_A_WITH_TILDE					0x00E3 /* a~ */
#define UTF_L_SMALL_LETTER_A_WITH_DIAERESIS				0x00E4 /* aÅN */
#define UTF_L_SMALL_LETTER_A_WITH_RING_ABOVE			0x00E5 /* aÅã */
#define UTF_L_SMALL_LETTER_AE							0x00E6 /* ae */
#define UTF_L_SMALL_LETTER_C_WITH_CEDILLA				0x00E7 /* cÅC */
#define UTF_L_SMALL_LETTER_E_WITH_GRAVE					0x00E8 /* e` */
#define UTF_L_SMALL_LETTER_E_WITH_ACUTE					0x00E9 /* eÅL */
#define UTF_L_SMALL_LETTER_E_WITH_CIRCUMFLEX			0x00EA /* e^ */
#define UTF_L_SMALL_LETTER_E_WITH_DIAERESIS				0x00EB /* eÅN */
#define UTF_L_SMALL_LETTER_I_WITH_GRAVE					0x00EC /* i` */
#define UTF_L_SMALL_LETTER_I_WITH_ACUTE					0x00ED /* iÅL */
#define UTF_L_SMALL_LETTER_I_WITH_CIRCUMFLEX			0x00EE /* i^ */
#define UTF_L_SMALL_LETTER_I_WITH_DIAERESIS				0x00EF /* iÅN */
#define UTF_L_SMALL_LETTER_ETH							0x00F0 /* d */
#define UTF_L_SMALL_LETTER_N_WITH_TILDE					0x00F1 /* n~ */
#define UTF_L_SMALL_LETTER_O_WITH_GRAVE					0x00F2 /* o` */
#define UTF_L_SMALL_LETTER_O_WITH_ACUTE					0x00F3 /* oÅL */
#define UTF_L_SMALL_LETTER_O_WITH_CIRCUMFLEX			0x00F4 /* o^ */
#define UTF_L_SMALL_LETTER_O_WITH_TILDE					0x00F5 /* o~ */
#define UTF_L_SMALL_LETTER_O_WITH_DIAERESIS				0x00F6 /* oÅN */
#define UTF_L_DIVISION_SIGN								0x00F7 /* ÅÄ */
#define UTF_L_SMALL_LETTER_O_WITH_STROKE				0x00F8 /* o/ */
#define UTF_L_SMALL_LETTER_U_WITH_GRAVE					0x00F9 /* u` */
#define UTF_L_SMALL_LETTER_U_WITH_ACUTE					0x00FA /* uÅL */
#define UTF_L_SMALL_LETTER_U_WITH_CIRCUMFLEX			0x00FB /* u^ */
#define UTF_L_SMALL_LETTER_U_WITH_DIAERESIS				0x00FC /* uÅN */
#define UTF_L_SMALL_LETTER_Y_WITH_ACUTE					0x00FD /* yÅL */
#define UTF_L_SMALL_LETTER_THORN						0x00FE /* t */
#define UTF_L_SMALL_LETTER_Y_WITH_DIAERESIS				0x00FF /* yÅN */

/* LATIN EXTENDED-A */
#define UTF_L_CAPITAL_LIGATURE							0x0152 /* OE */
#define UTF_L_SMALL_LIGATURE							0x0153 /* oe */

/* SPACING MODIFIER LETTERS */
#define UTF_SMALL_TILDE									0x02DC /* ~ */



/* Ç–ÇÁÇ™Ç»ÅEÉJÉ^ÉJÉiãLçÜ */
#define UTF_IDEOGRAPHIC_COMMA							0x3001 /* ÅA */
#define UTF_IDEOGRAPHIC_FULL_STOP						0x3002 /* ÅB */

/* Ç–ÇÁÇ™Ç» */
#define UTF_H_LETTER_SMALL_A							0x3041 /* Çü */
#define UTF_H_LETTER_A									0x3042 /* Ç† */
#define UTF_H_LETTER_SMALL_I							0x3043 /* Ç° */
#define UTF_H_LETTER_I									0x3044 /* Ç¢ */
#define UTF_H_LETTER_SMALL_U							0x3045 /* Ç£ */
#define UTF_H_LETTER_U									0x3046 /* Ç§ */
#define UTF_H_LETTER_SMALL_E							0x3047 /* Ç• */
#define UTF_H_LETTER_E									0x3048 /* Ç¶ */
#define UTF_H_LETTER_SMALL_O							0x3049 /* Çß */
#define UTF_H_LETTER_O									0x304A /* Ç® */
#define UTF_H_LETTER_KA									0x304B /* Ç© */
#define UTF_H_LETTER_GA									0x304C /* Ç™ */
#define UTF_H_LETTER_KI									0x304D /* Ç´ */
#define UTF_H_LETTER_GI									0x304E /* Ç¨ */
#define UTF_H_LETTER_KU									0x304F /* Ç≠ */
#define UTF_H_LETTER_GU									0x3050 /* ÇÆ */
#define UTF_H_LETTER_KE									0x3051 /* ÇØ */
#define UTF_H_LETTER_GE									0x3052 /* Ç∞ */
#define UTF_H_LETTER_KO									0x3053 /* Ç± */
#define UTF_H_LETTER_GO									0x3054 /* Ç≤ */
#define UTF_H_LETTER_SA									0x3055 /* Ç≥ */
#define UTF_H_LETTER_ZA									0x3056 /* Ç¥ */
#define UTF_H_LETTER_SI									0x3057 /* Çµ */
#define UTF_H_LETTER_ZI									0x3058 /* Ç∂ */
#define UTF_H_LETTER_SU									0x3059 /* Ç∑ */
#define UTF_H_LETTER_ZU									0x305A /* Ç∏ */
#define UTF_H_LETTER_SE									0x305B /* Çπ */
#define UTF_H_LETTER_ZE									0x305C /* Ç∫ */
#define UTF_H_LETTER_SO									0x305D /* Çª */
#define UTF_H_LETTER_ZO									0x305E /* Çº */
#define UTF_H_LETTER_TA									0x305F /* ÇΩ */
#define UTF_H_LETTER_DA									0x3060 /* Çæ */
#define UTF_H_LETTER_TI									0x3061 /* Çø */
#define UTF_H_LETTER_DI									0x3062 /* Ç¿ */
#define UTF_H_LETTER_SMALL_TU							0x3063 /* Ç¡ */
#define UTF_H_LETTER_TU									0x3064 /* Ç¬ */
#define UTF_H_LETTER_DU									0x3065 /* Ç√ */
#define UTF_H_LETTER_TE									0x3066 /* Çƒ */
#define UTF_H_LETTER_DE									0x3067 /* Ç≈ */
#define UTF_H_LETTER_TO									0x3068 /* Ç∆ */
#define UTF_H_LETTER_DO									0x3069 /* Ç« */
#define UTF_H_LETTER_NA									0x306A /* Ç» */
#define UTF_H_LETTER_NI									0x306B /* Ç… */
#define UTF_H_LETTER_NU									0x306C /* Ç  */
#define UTF_H_LETTER_NE									0x306D /* ÇÀ */
#define UTF_H_LETTER_NO									0x306E /* ÇÃ */
#define UTF_H_LETTER_HA									0x306F /* ÇÕ */
#define UTF_H_LETTER_BA									0x3070 /* ÇŒ */
#define UTF_H_LETTER_PA									0x3071 /* Çœ */
#define UTF_H_LETTER_HI									0x3072 /* Ç– */
#define UTF_H_LETTER_BI									0x3073 /* Ç— */
#define UTF_H_LETTER_PI									0x3074 /* Ç“ */
#define UTF_H_LETTER_HU									0x3075 /* Ç” */
#define UTF_H_LETTER_BU									0x3076 /* Ç‘ */
#define UTF_H_LETTER_PU									0x3077 /* Ç’ */
#define UTF_H_LETTER_HE									0x3078 /* Ç÷ */
#define UTF_H_LETTER_BE									0x3079 /* Ç◊ */
#define UTF_H_LETTER_PE									0x307A /* Çÿ */
#define UTF_H_LETTER_HO									0x307B /* ÇŸ */
#define UTF_H_LETTER_BO									0x307C /* Ç⁄ */
#define UTF_H_LETTER_PO									0x307D /* Ç€ */
#define UTF_H_LETTER_MA									0x307E /* Ç‹ */
#define UTF_H_LETTER_MI									0x307F /* Ç› */
#define UTF_H_LETTER_MU									0x3080 /* Çﬁ */
#define UTF_H_LETTER_ME									0x3081 /* Çﬂ */
#define UTF_H_LETTER_MO									0x3082 /* Ç‡ */
#define UTF_H_LETTER_SMALL_YA							0x3083 /* Ç· */
#define UTF_H_LETTER_YA									0x3084 /* Ç‚ */
#define UTF_H_LETTER_SMALL_YU							0x3085 /* Ç„ */
#define UTF_H_LETTER_YU									0x3086 /* Ç‰ */
#define UTF_H_LETTER_SMALL_YO							0x3087 /* ÇÂ */
#define UTF_H_LETTER_YO									0x3088 /* ÇÊ */
#define UTF_H_LETTER_RA									0x3089 /* ÇÁ */
#define UTF_H_LETTER_RI									0x308A /* ÇË */
#define UTF_H_LETTER_RU									0x308B /* ÇÈ */
#define UTF_H_LETTER_RE									0x308C /* ÇÍ */
#define UTF_H_LETTER_RO									0x308D /* ÇÎ */
#define UTF_H_LETTER_SMALL_WA							0x308E /* ÇÏ */
#define UTF_H_LETTER_WA									0x308F /* ÇÌ */
#define UTF_H_LETTER_WI									0x3090 /* ÇÓ */
#define UTF_H_LETTER_WE									0x3091 /* ÇÔ */
#define UTF_H_LETTER_WO									0x3092 /* Ç */
#define UTF_H_LETTER_N									0x3093 /* ÇÒ */
#define UTF_H_LETTER_VU									0x3094 /* Ç§"*/
#define UTF_KH_VOICED_SOUND_MARK						0x309B /* ë˜ì_ */
#define UTF_KH_SEMI_VOICED_SOUND_MARK					0x309C /* îºë˜ì_ */


/* ÉJÉ^ÉJÉi */
#define UTF_K_LETTER_SMALL_A							0x30A1 /* É@ */
#define UTF_K_LETTER_A									0x30A2 /* ÉA */
#define UTF_K_LETTER_SMALL_I							0x30A3 /* ÉB */
#define UTF_K_LETTER_I									0x30A4 /* ÉC */
#define UTF_K_LETTER_SMALL_U							0x30A5 /* ÉD */
#define UTF_K_LETTER_U									0x30A6 /* ÉE */
#define UTF_K_LETTER_SMALL_E							0x30A7 /* ÉF */
#define UTF_K_LETTER_E									0x30A8 /* ÉG */
#define UTF_K_LETTER_SMALL_O							0x30A9 /* ÉH */
#define UTF_K_LETTER_O									0x30AA /* ÉI */
#define UTF_K_LETTER_KA									0x30AB /* ÉJ */
#define UTF_K_LETTER_GA									0x30AC /* ÉK */
#define UTF_K_LETTER_KI									0x30AD /* ÉL */
#define UTF_K_LETTER_GI									0x30AE /* ÉM */
#define UTF_K_LETTER_KU									0x30AF /* ÉN */
#define UTF_K_LETTER_GU									0x30B0 /* ÉO */
#define UTF_K_LETTER_KE									0x30B1 /* ÉP */
#define UTF_K_LETTER_GE									0x30B2 /* ÉQ */
#define UTF_K_LETTER_KO									0x30B3 /* ÉR */
#define UTF_K_LETTER_GO									0x30B4 /* ÉS */
#define UTF_K_LETTER_SA									0x30B5 /* ÉT */
#define UTF_K_LETTER_ZA									0x30B6 /* ÉU */
#define UTF_K_LETTER_SI									0x30B7 /* ÉV */
#define UTF_K_LETTER_ZI									0x30B8 /* ÉW */
#define UTF_K_LETTER_SU									0x30B9 /* ÉX */
#define UTF_K_LETTER_ZU									0x30BA /* ÉY */
#define UTF_K_LETTER_SE									0x30BB /* ÉZ */
#define UTF_K_LETTER_ZE									0x30BC /* É[ */
#define UTF_K_LETTER_SO									0x30BD /* É\ */
#define UTF_K_LETTER_ZO									0x30BE /* É] */
#define UTF_K_LETTER_TA									0x30BF /* É^ */
#define UTF_K_LETTER_DA									0x30C0 /* É_ */
#define UTF_K_LETTER_TI									0x30C1 /* É` */
#define UTF_K_LETTER_DI									0x30C2 /* Éa */
#define UTF_K_LETTER_SMALL_TU							0x30C3 /* Éb */
#define UTF_K_LETTER_TU									0x30C4 /* Éc */
#define UTF_K_LETTER_DU									0x30C5 /* Éd */
#define UTF_K_LETTER_TE									0x30C6 /* Ée */
#define UTF_K_LETTER_DE									0x30C7 /* Éf */
#define UTF_K_LETTER_TO									0x30C8 /* Ég */
#define UTF_K_LETTER_DO									0x30C9 /* Éh */
#define UTF_K_LETTER_NA									0x30CA /* Éi */
#define UTF_K_LETTER_NI									0x30CB /* Éj */
#define UTF_K_LETTER_NU									0x30CC /* Ék */
#define UTF_K_LETTER_NE									0x30CD /* Él */
#define UTF_K_LETTER_NO									0x30CE /* Ém */
#define UTF_K_LETTER_HA									0x30CF /* Én */
#define UTF_K_LETTER_BA									0x30D0 /* Éo */
#define UTF_K_LETTER_PA									0x30D1 /* Ép */
#define UTF_K_LETTER_HI									0x30D2 /* Éq */
#define UTF_K_LETTER_BI									0x30D3 /* Ér */
#define UTF_K_LETTER_PI									0x30D4 /* És */
#define UTF_K_LETTER_HU									0x30D5 /* Ét */
#define UTF_K_LETTER_BU									0x30D6 /* Éu */
#define UTF_K_LETTER_PU									0x30D7 /* Év */
#define UTF_K_LETTER_HE									0x30D8 /* Éw */
#define UTF_K_LETTER_BE									0x30D9 /* Éx */
#define UTF_K_LETTER_PE									0x30DA /* Éy */
#define UTF_K_LETTER_HO									0x30DB /* Éz */
#define UTF_K_LETTER_BO									0x30DC /* É{ */
#define UTF_K_LETTER_PO									0x30DD /* É| */
#define UTF_K_LETTER_MA									0x30DE /* É} */
#define UTF_K_LETTER_MI									0x30DF /* É~ */
#define UTF_K_LETTER_MU									0x30E0 /* ÉÄ */
#define UTF_K_LETTER_ME									0x30E1 /* ÉÅ */
#define UTF_K_LETTER_MO									0x30E2 /* ÉÇ */
#define UTF_K_LETTER_SMALL_YA							0x30E3 /* ÉÉ */
#define UTF_K_LETTER_YA									0x30E4 /* ÉÑ */
#define UTF_K_LETTER_SMALL_YU							0x30E5 /* ÉÖ */
#define UTF_K_LETTER_YU									0x30E6 /* ÉÜ */
#define UTF_K_LETTER_SMALL_YO							0x30E7 /* Éá */
#define UTF_K_LETTER_YO									0x30E8 /* Éà */
#define UTF_K_LETTER_RA									0x30E9 /* Éâ */
#define UTF_K_LETTER_RI									0x30EA /* Éä */
#define UTF_K_LETTER_RU									0x30EB /* Éã */
#define UTF_K_LETTER_RE									0x30EC /* Éå */
#define UTF_K_LETTER_RO									0x30ED /* Éç */
#define UTF_K_LETTER_SMALL_WA							0x30EE /* Éé */
#define UTF_K_LETTER_WA									0x30EF /* Éè */
#define UTF_K_LETTER_WI									0x30F0 /* Éê */
#define UTF_K_LETTER_WE									0x30F1 /* Éë */
#define UTF_K_LETTER_WO									0x30F2 /* Éí */
#define UTF_K_LETTER_N									0x30F3 /* Éì */
#define UTF_K_LETTER_VU									0x30F4 /* Éî */
#define UTF_K_MIDDLE_DOT								0x30FB /* ÅE */
#define UTF_KH_PROLONGED_SOUND_MARK						0x30FC /* Å[ */

/* îºäpÅEëSäp */
#define UTF_FULLWIDTH_EXCLAMATION_MARK					0xFF01 /* ÅI */
#define UTF_FULLWIDTH_QUESTION_MARK						0xFF1F /* ÅH */
#define UTF_HALFWIDTH_L_CORNER_BRACKET					0xFF62 /* Åu */
#define UTF_HALFWIDTH_R_CORNER_BRACKET					0xFF63 /* Åv */


#endif /* __UTF16_CHAR_H__ */
