imagecnv.exe -f img\ic_1.SVG -i IC_1 > image_resource.c
imagecnv.exe -f img\ic_3200B.SVG -i IC_3200B >> image_resource.c
imagecnv.exe -f img\ic_2500B.SVG -i IC_2500B >> image_resource.c
imagecnv.exe -f img\ic_800B.SVG -i IC_800B >> image_resource.c
imagecnv.exe -f img\ic_ch1_btn.SVG -i IC_CH1_BTN >> image_resource.c
imagecnv.exe -f img\ic_ch2_btn.SVG -i IC_CH2_BTN >> image_resource.c
imagecnv.exe -f img\ic_dB.SVG -i IC_DB >> image_resource.c
imagecnv.exe -f img\ic_deg.SVG -i IC_DEG >> image_resource.c
imagecnv.exe -f img\ic_fps.SVG -i IC_FPS >> image_resource.c
imagecnv.exe -f img\ic_ftp.SVG -i IC_FTP >> image_resource.c
imagecnv.exe -f img\ic_HIGH.SVG -i IC_HIGH >> image_resource.c
imagecnv.exe -f img\ic_ISO.SVG -i IC_ISO >> image_resource.c
imagecnv.exe -f img\ic_K.SVG -i IC_K >> image_resource.c
imagecnv.exe -f img\ic_NATIVE.SVG -i IC_NATIVE >> image_resource.c
imagecnv.exe -f img\ic_NORMAL.SVG -i IC_NORMAL >> image_resource.c
imagecnv.exe -f img\ic_sec.SVG -i IC_SEC >> image_resource.c
imagecnv.exe -f img\ic_VFR.SVG -i IC_VFR >> image_resource.c
imagecnv.exe -f img\ic_alert.SVG -i IC_ALERT >> image_resource.c
imagecnv.exe -f img\ic_mute.SVG -i IC_MUTE >> image_resource.c
imagecnv.exe -f img\ic_warning.SVG -i IC_WARNING >> image_resource.c
imagecnv.exe -f img\ic_ch1_level_disable.SVG -i IC_CH1_LEVEL_DISABLE >> image_resource.c
imagecnv.exe -f img\ic_ch1_level_normal.SVG -i IC_CH1_LEVEL_NORMAL >> image_resource.c
imagecnv.exe -f img\ic_ch2_level_disable.SVG -i IC_CH2_LEVEL_DISABLE >> image_resource.c
imagecnv.exe -f img\ic_ch2_level_normal.SVG -i IC_CH2_LEVEL_NORMAL >> image_resource.c
imagecnv.exe -f img\ic_level_set.SVG -i IC_LEVEL_SET >> image_resource.c
imagecnv.exe -f img\ic_bottom_center.SVG -i IC_BOTTOM_CENTER >> image_resource.c
imagecnv.exe -f img\ic_bottom_left.SVG -i IC_BOTTOM_LEFT >> image_resource.c
imagecnv.exe -f img\ic_bottom_right.SVG -i IC_BOTTOM_RIGHT >> image_resource.c
imagecnv.exe -f img\ic_top_center.SVG -i IC_TOP_CENTER >> image_resource.c
imagecnv.exe -f img\ic_top_left.SVG -i IC_TOP_LEFT >> image_resource.c
imagecnv.exe -f img\ic_top_right.SVG -i IC_TOP_RIGHT >> image_resource.c
imagecnv.exe -f img\ic_ac.SVG -i IC_AC >> image_resource.c
imagecnv.exe -f img\ic_batt_lv0_red.SVG -i IC_BATT_LV0_RED >> image_resource.c
imagecnv.exe -f img\ic_batt_lv1.SVG -i IC_BATT_LV1 >> image_resource.c
imagecnv.exe -f img\ic_batt_lv2.SVG -i IC_BATT_LV2 >> image_resource.c
imagecnv.exe -f img\ic_batt_lv3.SVG -i IC_BATT_LV3 >> image_resource.c
imagecnv.exe -f img\ic_batt_lv4.SVG -i IC_BATT_LV4 >> image_resource.c
imagecnv.exe -f img\ic_batt_lv5.SVG -i IC_BATT_LV5 >> image_resource.c
imagecnv.exe -f img\ic_outputx1.SVG -i IC_OUTPUTX1 >> image_resource.c
imagecnv.exe -f img\ic_outputx3.SVG -i IC_OUTPUTX3 >> image_resource.c
imagecnv.exe -f img\ic_preset.SVG -i IC_PRESET >> image_resource.c
imagecnv.exe -f img\ic_slot1_sd_off.SVG -i IC_SLOT1_SD_OFF >> image_resource.c
imagecnv.exe -f img\ic_slot1_sd_on.SVG -i IC_SLOT1_SD_ON >> image_resource.c
imagecnv.exe -f img\ic_slot2_sd_off.SVG -i IC_SLOT2_SD_OFF >> image_resource.c
imagecnv.exe -f img\ic_slot2_sd_on.SVG -i IC_SLOT2_SD_ON >> image_resource.c
imagecnv.exe -f img\ic_backgr_off.SVG -i IC_BACKGR_OFF >> image_resource.c
imagecnv.exe -f img\ic_backgr_on.SVG -i IC_BACKGR_ON >> image_resource.c
imagecnv.exe -f img\ic_intrvl.SVG -i IC_INTRVL >> image_resource.c
imagecnv.exe -f img\ic_loop.SVG -i IC_LOOP >> image_resource.c
imagecnv.exe -f img\ic_relay_off.SVG -i IC_RELAY_OFF >> image_resource.c
imagecnv.exe -f img\ic_relay_on.SVG -i IC_RELAY_ON >> image_resource.c
imagecnv.exe -f img\ic_simul_off.SVG -i IC_SIMUL_OFF >> image_resource.c
imagecnv.exe -f img\ic_simul__on.SVG -i IC_SIMUL__ON >> image_resource.c
imagecnv.exe -f img\ic_slot1.SVG -i IC_SLOT1 >> image_resource.c
imagecnv.exe -f img\ic_slot2.SVG -i IC_SLOT2 >> image_resource.c
imagecnv.exe -f img\ic_sub_off.SVG -i IC_SUB_OFF >> image_resource.c
imagecnv.exe -f img\ic_sub_on.SVG -i IC_SUB_ON >> image_resource.c
imagecnv.exe -f img\ic_cut.SVG -i IC_CUT >> image_resource.c
imagecnv.exe -f img\ic_reel.SVG -i IC_REEL >> image_resource.c
imagecnv.exe -f img\ic_wifi_lv0.SVG -i IC_WIFI_LV0 >> image_resource.c
imagecnv.exe -f img\ic_wifi_lv1.SVG -i IC_WIFI_LV1 >> image_resource.c
imagecnv.exe -f img\ic_wifi_lv2.SVG -i IC_WIFI_LV2 >> image_resource.c
imagecnv.exe -f img\ic_wifi_lv3.SVG -i IC_WIFI_LV3 >> image_resource.c
imagecnv.exe -f img\ic_wifi_lv4.SVG -i IC_WIFI_LV4 >> image_resource.c
imagecnv.exe -f img\ic_wifi_off.SVG -i IC_WIFI_OFF >> image_resource.c
imagecnv.exe -f img\ic_wifi_rop_lv0.SVG -i IC_WIFI_ROP_LV0 >> image_resource.c
imagecnv.exe -f img\ic_wifi_rop_lv1.SVG -i IC_WIFI_ROP_LV1 >> image_resource.c
imagecnv.exe -f img\ic_wifi_rop_lv2.SVG -i IC_WIFI_ROP_LV2 >> image_resource.c
imagecnv.exe -f img\ic_wifi_rop_lv3.SVG -i IC_WIFI_ROP_LV3 >> image_resource.c
imagecnv.exe -f img\ic_wifi_rop_lv4.SVG -i IC_WIFI_ROP_LV4 >> image_resource.c
imagecnv.exe -f img\ic_menu_check.SVG -i IC_MENU_CHECK >> image_resource.c
imagecnv.exe -f img\ic_menu_down.SVG -i IC_MENU_DOWN >> image_resource.c
imagecnv.exe -f img\ic_menu_level_large_off.SVG -i IC_MENU_LEVEL_LARGE_OFF >> image_resource.c
imagecnv.exe -f img\ic_menu_level_large_on.SVG -i IC_MENU_LEVEL_LARGE_ON >> image_resource.c
imagecnv.exe -f img\ic_menu_level_small_off.SVG -i IC_MENU_LEVEL_SMALL_OFF >> image_resource.c
imagecnv.exe -f img\ic_menu_level_small_on.SVG -i IC_MENU_LEVEL_SMALL_ON >> image_resource.c
imagecnv.exe -f img\ic_menu_return.SVG -i IC_MENU_RETURN >> image_resource.c
imagecnv.exe -f img\ic_menu_set.SVG -i IC_MENU_SET >> image_resource.c
imagecnv.exe -f img\ic_menu_up.SVG -i IC_MENU_UP >> image_resource.c
imagecnv.exe -f img\textbox_menu_spin_box_1_1_adjust.SVG -i TEXTBOX_MENU_SPIN_BOX_1_1_ADJUST >> image_resource.c
imagecnv.exe -f img\textbox_menu_spin_box_1_1_selected.SVG -i TEXTBOX_MENU_SPIN_BOX_1_1_SELECTED >> image_resource.c
imagecnv.exe -f img\textbox_menu_spin_box_1_2_adjust.SVG -i TEXTBOX_MENU_SPIN_BOX_1_2_ADJUST >> image_resource.c
imagecnv.exe -f img\textbox_menu_spin_box_1_2_selected.SVG -i TEXTBOX_MENU_SPIN_BOX_1_2_SELECTED >> image_resource.c
imagecnv.exe -f img\textbox_menu_spin_box_1_3.SVG -i TEXTBOX_MENU_SPIN_BOX_1_3 >> image_resource.c
imagecnv.exe -f img\ic_menu_kb_left.SVG -i IC_MENU_KB_LEFT >> image_resource.c
imagecnv.exe -f img\ic_menu_kb_right.SVG -i IC_MENU_KB_RIGHT >> image_resource.c
imagecnv.exe -f img\ic_menu_kb_space.SVG -i IC_MENU_KB_SPACE >> image_resource.c
imagecnv.exe -f img\ic_settings_update_arrow.SVG -i IC_SETTINGS_UPDATE_ARROW >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_copy_arrow.SVG -i IC_THUMBNAIL_COPY_ARROW >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_2k_23p.SVG -i IC_THUMBNAIL_FORMAT_2K_23P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_2k_24p.SVG -i IC_THUMBNAIL_FORMAT_2K_24P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_2k_25p.SVG -i IC_THUMBNAIL_FORMAT_2K_25P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_2k_29p.SVG -i IC_THUMBNAIL_FORMAT_2K_29P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_2k_50p.SVG -i IC_THUMBNAIL_FORMAT_2K_50P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_2k_59p.SVG -i IC_THUMBNAIL_FORMAT_2K_59P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_4k_23p.SVG -i IC_THUMBNAIL_FORMAT_4K_23P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_4k_24p.SVG -i IC_THUMBNAIL_FORMAT_4K_24P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_4k_25p.SVG -i IC_THUMBNAIL_FORMAT_4K_25P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_4k_29p.SVG -i IC_THUMBNAIL_FORMAT_4K_29P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_4k_50p.SVG -i IC_THUMBNAIL_FORMAT_4K_50P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_4k_59p.SVG -i IC_THUMBNAIL_FORMAT_4K_59P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_fhd_23p.SVG -i IC_THUMBNAIL_FORMAT_FHD_23P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_fhd_25p.SVG -i IC_THUMBNAIL_FORMAT_FHD_25P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_fhd_29p.SVG -i IC_THUMBNAIL_FORMAT_FHD_29P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_fhd_50i.SVG -i IC_THUMBNAIL_FORMAT_FHD_50I >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_fhd_50p.SVG -i IC_THUMBNAIL_FORMAT_FHD_50P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_fhd_59i.SVG -i IC_THUMBNAIL_FORMAT_FHD_59I >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_fhd_59p.SVG -i IC_THUMBNAIL_FORMAT_FHD_59P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ha_50i.SVG -i IC_THUMBNAIL_FORMAT_HA_50I >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ha_59i.SVG -i IC_THUMBNAIL_FORMAT_HA_59I >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ha_50p.SVG -i IC_THUMBNAIL_FORMAT_HA_50P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ha_59p.SVG -i IC_THUMBNAIL_FORMAT_HA_59P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ph_23p.SVG -i IC_THUMBNAIL_FORMAT_PH_23P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ph_50i.SVG -i IC_THUMBNAIL_FORMAT_PH_50I >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ph_59i.SVG -i IC_THUMBNAIL_FORMAT_PH_59I >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_pm_50p.SVG -i IC_THUMBNAIL_FORMAT_PM_50P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_pm_59p.SVG -i IC_THUMBNAIL_FORMAT_PM_59P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ps_50p.SVG -i IC_THUMBNAIL_FORMAT_PS_50P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ps_59p.SVG -i IC_THUMBNAIL_FORMAT_PS_59P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_sub_23p.SVG -i IC_THUMBNAIL_FORMAT_SUB_23P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_sub_24p.SVG -i IC_THUMBNAIL_FORMAT_SUB_24P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_sub_25p.SVG -i IC_THUMBNAIL_FORMAT_SUB_25P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_sub_29p.SVG -i IC_THUMBNAIL_FORMAT_SUB_29P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_sub_50p.SVG -i IC_THUMBNAIL_FORMAT_SUB_50P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_sub_59p.SVG -i IC_THUMBNAIL_FORMAT_SUB_59P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_uhd_23p.SVG -i IC_THUMBNAIL_FORMAT_UHD_23P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_uhd_25p.SVG -i IC_THUMBNAIL_FORMAT_UHD_25P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_uhd_29p.SVG -i IC_THUMBNAIL_FORMAT_UHD_29P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_uhd_50p.SVG -i IC_THUMBNAIL_FORMAT_UHD_50P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_uhd_59p.SVG -i IC_THUMBNAIL_FORMAT_UHD_59P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_del.SVG -i IC_THUMBNAIL_DEL >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_exec.SVG -i IC_THUMBNAIL_EXEC >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_keytop_copy.SVG -i IC_THUMBNAIL_KEYTOP_COPY >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_media_sd_1_none.SVG -i IC_THUMBNAIL_MEDIA_SD_1_NONE >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_media_sd_1_normal.SVG -i IC_THUMBNAIL_MEDIA_SD_1_NORMAL >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_media_sd_1_selected.SVG -i IC_THUMBNAIL_MEDIA_SD_1_SELECTED >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_media_sd_2_none.SVG -i IC_THUMBNAIL_MEDIA_SD_2_NONE >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_media_sd_2_normal.SVG -i IC_THUMBNAIL_MEDIA_SD_2_NORMAL >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_media_sd_2_selected.SVG -i IC_THUMBNAIL_MEDIA_SD_2_SELECTED >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_media_sd_error.SVG -i IC_THUMBNAIL_MEDIA_SD_ERROR >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_mode_avchd_normal.SVG -i IC_THUMBNAIL_MODE_AVCHD_NORMAL >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_mode_avchd_selected.SVG -i IC_THUMBNAIL_MODE_AVCHD_SELECTED >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_mode_mov_normal.SVG -i IC_THUMBNAIL_MODE_MOV_NORMAL >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_mode_mov_selected.SVG -i IC_THUMBNAIL_MODE_MOV_SELECTED >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_clip_disable.SVG -i IC_THUMBNAIL_CLIP_DISABLE >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_copy.SVG -i IC_THUMBNAIL_COPY >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_delete.SVG -i IC_THUMBNAIL_DELETE >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_Impossible_to_play.SVG -i IC_THUMBNAIL_IMPOSSIBLE_TO_PLAY >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_protect.SVG -i IC_THUMBNAIL_PROTECT >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_resume.SVG -i IC_THUMBNAIL_RESUME >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_selected.SVG -i IC_THUMBNAIL_SELECTED >> image_resource.c
imagecnv.exe -f img\ic_osd_ac.SVG -i IC_OSD_AC >> image_resource.c
imagecnv.exe -f img\ic_osd_batt_lv0_red.SVG -i IC_OSD_BATT_LV0_RED >> image_resource.c
imagecnv.exe -f img\ic_osd_batt_lv1.SVG -i IC_OSD_BATT_LV1 >> image_resource.c
imagecnv.exe -f img\ic_osd_batt_lv2.SVG -i IC_OSD_BATT_LV2 >> image_resource.c
imagecnv.exe -f img\ic_osd_batt_lv3.SVG -i IC_OSD_BATT_LV3 >> image_resource.c
imagecnv.exe -f img\ic_osd_batt_lv4.SVG -i IC_OSD_BATT_LV4 >> image_resource.c
imagecnv.exe -f img\ic_osd_batt_lv5.SVG -i IC_OSD_BATT_LV5 >> image_resource.c
imagecnv.exe -f img\ic_osd_keytop_ff.SVG -i IC_OSD_KEYTOP_FF >> image_resource.c
imagecnv.exe -f img\ic_osd_keytop_frame_advance.SVG -i IC_OSD_KEYTOP_FRAME_ADVANCE >> image_resource.c
imagecnv.exe -f img\ic_osd_keytop_frame_return.SVG -i IC_OSD_KEYTOP_FRAME_RETURN >> image_resource.c
imagecnv.exe -f img\ic_osd_keytop_play_still.SVG -i IC_OSD_KEYTOP_PLAY_STILL >> image_resource.c
imagecnv.exe -f img\ic_osd_keytop_rew.SVG -i IC_OSD_KEYTOP_REW >> image_resource.c
imagecnv.exe -f img\ic_osd_keytop_stop.SVG -i IC_OSD_KEYTOP_STOP >> image_resource.c
imagecnv.exe -f img\ic_osd_audio_rec_off.SVG -i IC_OSD_AUDIO_REC_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_ch1_ch2.SVG -i IC_OSD_CH1_CH2 >> image_resource.c
imagecnv.exe -f img\ic_osd_preset.SVG -i IC_OSD_PRESET >> image_resource.c
imagecnv.exe -f img\ic_osd_rec.SVG -i IC_OSD_REC >> image_resource.c
imagecnv.exe -f img\ic_osd_rec_sdi_hdmi.SVG -i IC_OSD_REC_SDI_HDMI >> image_resource.c
imagecnv.exe -f img\ic_osd_slider_btn.SVG -i IC_OSD_SLIDER_BTN >> image_resource.c
imagecnv.exe -f img\ic_osd_dzoom.SVG -i IC_OSD_DZOOM >> image_resource.c
imagecnv.exe -f img\ic_osd_eis.SVG -i IC_OSD_EIS >> image_resource.c
imagecnv.exe -f img\ic_osd_min.SVG -i IC_OSD_MIN >> image_resource.c
imagecnv.exe -f img\ic_osd_bos.SVG -i IC_OSD_BOS >> image_resource.c
imagecnv.exe -f img\ic_osd_eos.SVG -i IC_OSD_EOS >> image_resource.c
imagecnv.exe -f img\ic_osd_ffx10.SVG -i IC_OSD_FFX10 >> image_resource.c
imagecnv.exe -f img\ic_osd_ffx20.SVG -i IC_OSD_FFX20 >> image_resource.c
imagecnv.exe -f img\ic_osd_play.SVG -i IC_OSD_PLAY >> image_resource.c
imagecnv.exe -f img\ic_osd_rewx10.SVG -i IC_OSD_REWX10 >> image_resource.c
imagecnv.exe -f img\ic_osd_rewx20.SVG -i IC_OSD_REWX20 >> image_resource.c
imagecnv.exe -f img\ic_osd_slow_back.SVG -i IC_OSD_SLOW_BACK >> image_resource.c
imagecnv.exe -f img\ic_osd_slow_feed.SVG -i IC_OSD_SLOW_FEED >> image_resource.c
imagecnv.exe -f img\ic_osd_still.SVG -i IC_OSD_STILL >> image_resource.c
imagecnv.exe -f img\ic_osd_stop.SVG -i IC_OSD_STOP >> image_resource.c
imagecnv.exe -f img\ic_osd_slot1_sd_off.SVG -i IC_OSD_SLOT1_SD_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_slot1_sd_on.SVG -i IC_OSD_SLOT1_SD_ON >> image_resource.c
imagecnv.exe -f img\ic_osd_slot2_sd_off.SVG -i IC_OSD_SLOT2_SD_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_slot2_sd_on.SVG -i IC_OSD_SLOT2_SD_ON >> image_resource.c
imagecnv.exe -f img\ic_osd_backgr_off.SVG -i IC_OSD_BACKGR_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_backgr_on.SVG -i IC_OSD_BACKGR_ON >> image_resource.c
imagecnv.exe -f img\ic_osd_relay_off.SVG -i IC_OSD_RELAY_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_relay_on.SVG -i IC_OSD_RELAY_ON >> image_resource.c
imagecnv.exe -f img\ic_osd_simul_off.SVG -i IC_OSD_SIMUL_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_simul_on.SVG -i IC_OSD_SIMUL_ON >> image_resource.c
imagecnv.exe -f img\ic_osd_sub_off.SVG -i IC_OSD_SUB_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_sub_on.SVG -i IC_OSD_SUB_ON >> image_resource.c
imagecnv.exe -f img\ic_osd_wifi_lv0.SVG -i IC_OSD_WIFI_LV0 >> image_resource.c
imagecnv.exe -f img\ic_osd_wifi_lv1.SVG -i IC_OSD_WIFI_LV1 >> image_resource.c
imagecnv.exe -f img\ic_osd_wifi_lv2.SVG -i IC_OSD_WIFI_LV2 >> image_resource.c
imagecnv.exe -f img\ic_osd_wifi_lv3.SVG -i IC_OSD_WIFI_LV3 >> image_resource.c
imagecnv.exe -f img\ic_osd_wifi_lv4.SVG -i IC_OSD_WIFI_LV4 >> image_resource.c
imagecnv.exe -f img\ic_osd_wifi_off.SVG -i IC_OSD_WIFI_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_wifi_rop_lv0.SVG -i IC_OSD_WIFI_ROP_LV0 >> image_resource.c
imagecnv.exe -f img\ic_osd_wifi_rop_lv1.SVG -i IC_OSD_WIFI_ROP_LV1 >> image_resource.c
imagecnv.exe -f img\ic_osd_wifi_rop_lv2.SVG -i IC_OSD_WIFI_ROP_LV2 >> image_resource.c
imagecnv.exe -f img\ic_osd_wifi_rop_lv3.SVG -i IC_OSD_WIFI_ROP_LV3 >> image_resource.c
imagecnv.exe -f img\ic_osd_wifi_rop_lv4.SVG -i IC_OSD_WIFI_ROP_LV4 >> image_resource.c
imagecnv.exe -f img\ic_audio_bottom_center.SVG -i IC_AUDIO_BOTTOM_CENTER >> image_resource.c
imagecnv.exe -f img\ic_audio_bottom_left.SVG -i IC_AUDIO_BOTTOM_LEFT >> image_resource.c
imagecnv.exe -f img\ic_audio_bottom_right.SVG -i IC_AUDIO_BOTTOM_RIGHT >> image_resource.c
imagecnv.exe -f img\ic_audio_top_center.SVG -i IC_AUDIO_TOP_CENTER >> image_resource.c
imagecnv.exe -f img\ic_audio_top_left.SVG -i IC_AUDIO_TOP_LEFT >> image_resource.c
imagecnv.exe -f img\ic_audio_top_right.SVG -i IC_AUDIO_TOP_RIGHT >> image_resource.c
imagecnv.exe -f img\ic_info_bottom.SVG -i IC_INFO_BOTTOM >> image_resource.c
imagecnv.exe -f img\ic_info_top.SVG -i IC_INFO_TOP >> image_resource.c
imagecnv.exe -f img\ic_dur.SVG -i IC_DUR >> image_resource.c
imagecnv.exe -f img\ic_min.SVG -i IC_MIN >> image_resource.c
imagecnv.exe -f img\ic_tcg.SVG -i IC_TCG >> image_resource.c
imagecnv.exe -f img\ic_tcg_slave.SVG -i IC_TCG_SLAVE >> image_resource.c
imagecnv.exe -f img\ic_ubg.SVG -i IC_UBG >> image_resource.c
imagecnv.exe -f img\ic_lan_off.SVG -i IC_LAN_OFF >> image_resource.c
imagecnv.exe -f img\ic_lan_on.SVG -i IC_LAN_ON >> image_resource.c
imagecnv.exe -f img\ic_lan_on_rop.SVG -i IC_LAN_ON_ROP >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_420_50m.SVG -i IC_THUMBNAIL_FORMAT_420_50M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_420_100m.SVG -i IC_THUMBNAIL_FORMAT_420_100M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_420_150m.SVG -i IC_THUMBNAIL_FORMAT_420_150M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_422_50m.SVG -i IC_THUMBNAIL_FORMAT_422_50M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_422_100m.SVG -i IC_THUMBNAIL_FORMAT_422_100M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_422_150m.SVG -i IC_THUMBNAIL_FORMAT_422_150M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_alli_100m.SVG -i IC_THUMBNAIL_FORMAT_ALLI_100M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_alli_200m.SVG -i IC_THUMBNAIL_FORMAT_ALLI_200M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_alli_400m.SVG -i IC_THUMBNAIL_FORMAT_ALLI_400M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_avchd_ha.SVG -i IC_THUMBNAIL_FORMAT_AVCHD_HA >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_avchd_ph.SVG -i IC_THUMBNAIL_FORMAT_AVCHD_PH >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_avchd_pm.SVG -i IC_THUMBNAIL_FORMAT_AVCHD_PM >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_avchd_ps.SVG -i IC_THUMBNAIL_FORMAT_AVCHD_PS >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_avchd_sa.SVG -i IC_THUMBNAIL_FORMAT_AVCHD_SA >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_hevc_150m.SVG -i IC_THUMBNAIL_FORMAT_HEVC_150M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_hevc_200m.SVG -i IC_THUMBNAIL_FORMAT_HEVC_200M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_hd_50p.SVG -i IC_THUMBNAIL_FORMAT_HD_50P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_hd_59p.SVG -i IC_THUMBNAIL_FORMAT_HD_59P >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_sd_50i.SVG -i IC_THUMBNAIL_FORMAT_SD_50I >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_sd_59i.SVG -i IC_THUMBNAIL_FORMAT_SD_59I >> image_resource.c
imagecnv.exe -f img\ic_lv0.SVG -i IC_WIFI_AP_SIG_LV0 >> image_resource.c
imagecnv.exe -f img\ic_lv1.SVG -i IC_WIFI_AP_SIG_LV1 >> image_resource.c
imagecnv.exe -f img\ic_lv2.SVG -i IC_WIFI_AP_SIG_LV2 >> image_resource.c
imagecnv.exe -f img\ic_lv3.SVG -i IC_WIFI_AP_SIG_LV3 >> image_resource.c
imagecnv.exe -f img\ic_lv4.SVG -i IC_WIFI_AP_SIG_LV4 >> image_resource.c
imagecnv.exe -f img\ic_menu_arrow.SVG -i IC_MENU_ARROW >> image_resource.c
imagecnv.exe -f img\ic_osd_a_iris_back.SVG -i IC_OSD_A_IRIS_BACK >> image_resource.c
imagecnv.exe -f img\ic_osd_a_iris_spot.SVG -i IC_OSD_A_IRIS_SPOT >> image_resource.c
imagecnv.exe -f img\ic_osd_a_iris_std.SVG -i IC_OSD_A_IRIS_STD >> image_resource.c
imagecnv.exe -f img\ic_osd_af_area.SVG -i IC_OSD_AF_AREA >> image_resource.c
imagecnv.exe -f img\ic_osd_area.SVG -i IC_OSD_AREA >> image_resource.c
imagecnv.exe -f img\ic_osd_auto.SVG -i IC_OSD_AUTO >> image_resource.c
imagecnv.exe -f img\ic_osd_bonding_antenna_0.SVG -i IC_OSD_BONDING_ANTENNA_0 >> image_resource.c
imagecnv.exe -f img\ic_osd_bonding_antenna_1.SVG -i IC_OSD_BONDING_ANTENNA_1 >> image_resource.c
imagecnv.exe -f img\ic_osd_bonding_antenna_2.SVG -i IC_OSD_BONDING_ANTENNA_2 >> image_resource.c
imagecnv.exe -f img\ic_osd_bonding_antenna_3.SVG -i IC_OSD_BONDING_ANTENNA_3 >> image_resource.c
imagecnv.exe -f img\ic_osd_bonding_antenna_4.SVG -i IC_OSD_BONDING_ANTENNA_4 >> image_resource.c
imagecnv.exe -f img\ic_osd_bonding_antenna_5.SVG -i IC_OSD_BONDING_ANTENNA_5 >> image_resource.c
imagecnv.exe -f img\ic_osd_dial.SVG -i IC_OSD_DIAL >> image_resource.c
imagecnv.exe -f img\ic_osd_drs.SVG -i IC_OSD_DRS >> image_resource.c
imagecnv.exe -f img\ic_osd_hdr.SVG -i IC_OSD_HDR >> image_resource.c
imagecnv.exe -f img\ic_osd_lan_off.SVG -i IC_OSD_LAN_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_lan_on.SVG -i IC_OSD_LAN_ON >> image_resource.c
imagecnv.exe -f img\ic_osd_lan_on_rop.SVG -i IC_OSD_LAN_ON_ROP >> image_resource.c
imagecnv.exe -f img\ic_osd_level_off.SVG -i IC_OSD_LEVEL_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_level_on.SVG -i IC_OSD_LEVEL_ON >> image_resource.c
imagecnv.exe -f img\ic_osd_level_red.SVG -i IC_OSD_LEVEL_RED >> image_resource.c
imagecnv.exe -f img\ic_osd_macro.SVG -i IC_OSD_MACRO >> image_resource.c
imagecnv.exe -f img\ic_osd_prerec.SVG -i IC_OSD_PREREC >> image_resource.c
imagecnv.exe -f img\ic_osd_s_slow_100.SVG -i IC_OSD_S_SLOW_100 >> image_resource.c
imagecnv.exe -f img\ic_osd_s_slow_120.SVG -i IC_OSD_S_SLOW_120 >> image_resource.c
imagecnv.exe -f img\ic_osd_slot1_off.SVG -i IC_OSD_SLOT1_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_slot1_on.SVG -i IC_OSD_SLOT1_ON >> image_resource.c
imagecnv.exe -f img\ic_osd_slot2_off.SVG -i IC_OSD_SLOT2_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_slot2_on.SVG -i IC_OSD_SLOT2_ON >> image_resource.c
imagecnv.exe -f img\ic_osd_stream_off.SVG -i IC_OSD_STREAM_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_stream_standby.SVG -i IC_OSD_STREAM_STANDBY >> image_resource.c
imagecnv.exe -f img\ic_osd_streaming.SVG -i IC_OSD_STREAMING >> image_resource.c
imagecnv.exe -f img\ic_osd_vol_off.SVG -i IC_OSD_VOL_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_vol_on.SVG -i IC_OSD_VOL_ON >> image_resource.c
imagecnv.exe -f img\ic_osd_tarry_g.SVG -i IC_OSD_TARRY_G >> image_resource.c
imagecnv.exe -f img\ic_osd_dial_select.SVG -i IC_OSD_DIAL_SELECT >> image_resource.c
imagecnv.exe -f img\ic_osd_tebure.SVG -i IC_OSD_TEBURE >> image_resource.c
imagecnv.exe -f img\ic_osd_tebure_hybrid.SVG -i IC_OSD_TEBURE_HYBRID >> image_resource.c
imagecnv.exe -f img\ic_osd_fbc.SVG -i IC_OSD_FBC >> image_resource.c
imagecnv.exe -f img\ic_audio_level_red.SVG -i IC_AUDIO_LEVEL_RED >> image_resource.c
imagecnv.exe -f img\ic_audio_level_off.SVG -i IC_AUDIO_LEVEL_OFF >> image_resource.c
imagecnv.exe -f img\ic_audio_level_on.SVG -i IC_AUDIO_LEVEL_ON >> image_resource.c
imagecnv.exe -f img\ic_audio_ch1_ch2.SVG -i IC_AUDIO_CH1_CH2 >> image_resource.c
imagecnv.exe -f img\ic_audio_rec_off.SVG -i IC_AUDIO_REC_OFF >> image_resource.c
imagecnv.exe -f img\ic_osd_cap.SVG -i IC_OSD_CAP >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_hevc_100m.SVG -i IC_THUMBNAIL_FORMAT_HEVC_100M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ultra_422i.SVG -i IC_THUMBNAIL_FORMAT_ULTRA_422I >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ultra_50M.SVG -i IC_THUMBNAIL_FORMAT_ULTRA_50M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ultra_25m.SVG -i IC_THUMBNAIL_FORMAT_ULTRA_25M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_format_ultra_12m.SVG -i IC_THUMBNAIL_FORMAT_ULTRA_12M >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_mode_p2_normal.SVG -i IC_THUMBNAIL_MODE_P2_NORMAL >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_mode_p2_selected.SVG -i IC_THUMBNAIL_MODE_P2_SELECTED >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_p2_repairable.SVG -i IC_THUMBNAIL_P2_REPAIRABLE >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_p2_unrepairable.SVG -i IC_THUMBNAIL_P2_UNREPAIRABLE >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_p2_clip_repairable.SVG -i IC_THUMBNAIL_P2_CLIP_REPAIRABLE >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_p2_clip_unrepairable.SVG -i IC_THUMBNAIL_P2_CLIP_UNREPAIRABLE >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_p2_clip_unknown.SVG -i IC_THUMBNAIL_P2_CLIP_UNKNOWN >> image_resource.c
imagecnv.exe -f img\ic_thumbnail_p2_clip_reconnect.SVG -i IC_THUMBNAIL_P2_CLIP_RE_CONNECT >> image_resource.c
